// GameDistribution's genre taxonomy (categories filter values), plus our
// original curated set for backward compatibility with the hand-picked games.
export const CATEGORY_ICON: Record<string, string> = {
  // GameDistribution genres
  Casual: "🎮",
  Puzzle: "🧩",
  Adventure: "🗺️",
  "Dress-up": "👗",
  "Racing & Driving": "🏎️",
  Shooter: "🔫",
  Agility: "🤸",
  Simulation: "🛠️",
  Battle: "⚔️",
  Art: "🎨",
  "Match-3": "🍬",
  ".IO": "🌐",
  "Mahjong & Connect": "🀄",
  Strategy: "♟️",
  Care: "💖",
  Sports: "⚽",
  Cards: "🃏",
  Cooking: "🍳",
  Football: "🏈",
  "Bubble Shooter": "🫧",
  Merge: "🔗",
  Educational: "📚",
  Jigsaw: "🧩",
  Boardgames: "🎲",
  Basketball: "🏀",
  Quiz: "❓",

  // Original curated categories (kept for the hand-picked games)
  Racing: "🏎️",
  Arcade: "🕹️",
  Action: "🔫",
  Board: "🎲",
  ".io": "🌐",

  // GamePix categories
  "2048": "🔢",
  "Match 3": "🍬",
  "Hyper Casual": "👆",
  Zombie: "🧟",
  Trivia: "❓",
  Memory: "🧠",
  Fighting: "🥊",
  Math: "➗",
  Io: "🌐",
  Drawing: "✏️",
  Ball: "⚽",
  Animal: "🐾",
  Fun: "😄",
  "Games For Girls": "💅",
  "First Person Shooter": "🎯",
  Brain: "🧠",
  Christmas: "🎄",
  Platformer: "🍄",
  Car: "🚗",
  Block: "🧱",
  Clicker: "🖱️",
  Retro: "👾",
  Runner: "🏃",
  Monster: "👹",
  "Two Player": "👥",
  "Dress Up": "👗",
  Coloring: "🖍️",
  Skill: "🎯",
  "Jigsaw Puzzles": "🧩",
  Card: "🃏",
  Tanks: "🪖",
  Farming: "🚜",
  Building: "🏗️",
  Airplane: "✈️",
  Cats: "🐱",
  "Hidden Object": "🔍",
  Horror: "👻",
  Halloween: "🎃",
  Word: "🔤",
  Snake: "🐍",
  Tap: "👆",
  Escape: "🚪",
  Soccer: "⚽",
  Dinosaur: "🦖",
  Driving: "🚙",
  Addictive: "🔥",
  Tetris: "🟦",
};
